name: test-incuvers-iot-jy
version: '1.03'
summary: test-incuvers-iot-jy
description: |
  Simple test of a hello world flask app.
grade: stable

architectures:
  - build-on: arm64
    run-on: arm64

confinement: strict

base: core18

apps:
  test-incuvers-iot-jy:
      command: flask run --host=0.0.0.0
      daemon: simple
      restart-condition: always
      plugs: [home, network, network-bind]
      environment:
          FLASK_APP: $SNAP
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

  identity:
      command: python3 $SNAP/tcp_client.py
      daemon: simple
      restart-condition: always
      plugs: [home, network, network-bind]
      environment:
          LC_ALL: C.UTF-8
          LANG: C.UTF-8

parts:
  flask-app:
    plugin: python
    python-version: python3
    python-packages:
       [flask]
  identity:
    plugin: dump
    source: ./app/identity
  incuvers-app:
    plugin: dump
    source: ./app/incuvers-iot
